sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx9265a4ab0f86c974
    secret: 793b5b41e28384dc232e2594e16f9fab
